server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
  rabbitmq:
    host: localhost
    port: 15627